name: Publish
on:
  push:
    branches:
      - main
      - test_actions
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          registry-url: https://registry.npmjs.org
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: '1'

      - name: Install Dependencies
        run: corepack yarn install --immutable

      - name: Test
        run: corepack yarn test --ci --coverage

      - name: Provide auth
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./.yarnrc.yml
          contents: |
            npmAuthToken: '${{ secrets.NPM_TOKEN }}'
          write-mode: append

      - name: Build
        run: corepack yarn build

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: corepack yarn npm publish --access public
