name: Publish
on:
  push:
    branches:
      - main
      - test_actions
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --ci --coverage

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: npm publish --access public --//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
